version: '3'

services:
  debugBuild:
    image: ferus 
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: nimble debugBuild
  prodBuild:
    image: ferus 
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: nimble productionBuild
  ferus:
    image: ferus 
    build: .
    environment:
      - DISPLAY
    working_dir: /usr/src/app/bin
    volumes:
      - /tmp/X11-unix:/tmp/X11-unix
      - ./bin:/usr/src/app/bin
    command: ./ferus

