## WebIDL interface bound for Bali.
## Automatically generated by Niskriya N/A
##
## DO NOT MODIFY THIS! IT HAS BEEN MANUALLY EDITED TO CONTAIN SOME EXTRA FIELDS!

type JSEventTarget* = object
type JSEventListenerOptions* = object
  capture*: JSValue    # boolean

type JSAddEventListenerOptions* = object of JSEventListenerOptions
  passive*: JSValue    # boolean
  once*: JSValue    # boolean
  signal*: JSValue    # AbortSignal

type JSNode* = object of JSEventTarget
  

type JSGetRootNodeOptions* = object
  composed*: JSValue    # boolean

proc addEventListenerImpl*(self: JSEventTarget, kind: JSValue, callback: JSValue): JSValue
proc removeEventListenerImpl*(self: JSEventTarget, kind: JSValue, callback: JSValue): JSValue
proc dispatchEventImpl*(self: JSEventTarget, event: JSValue): JSValue
proc getRootNodeImpl*(self: JSNode, ): JSValue
proc hasChildNodesImpl*(self: JSNode, ): JSValue
proc normalizeImpl*(self: JSNode, ): JSValue
proc cloneNodeImpl*(self: JSNode, ): JSValue
proc isEqualNodeImpl*(self: JSNode, otherNode: JSValue): JSValue
proc isSameNodeImpl*(self: JSNode, otherNode: JSValue): JSValue
proc compareDocumentPositionImpl*(self: JSNode, other: JSValue): JSValue
proc containsImpl*(self: JSNode, other: JSValue): JSValue
proc lookupPrefixImpl*(self: JSNode, namespace: JSValue): JSValue
proc lookupNamespaceURIImpl*(self: JSNode, prefix: JSValue): JSValue
proc isDefaultNamespaceImpl*(self: JSNode, namespace: JSValue): JSValue
proc insertBeforeImpl*(self: JSNode, node: JSValue, child: JSValue): JSValue
proc appendChildImpl*(self: JSNode, node: JSValue): JSValue
proc replaceChildImpl*(self: JSNode, node: JSValue, child: JSValue): JSValue
proc removeChildImpl*(self: JSNode, child: JSValue): JSValue
